### ISSUE TITLE
Max Altitude at 39100 Feet?

### ISSUE THREAD

**Issue by SandaleAir** [headwindsim/aircraft#71]
### Aircraft Version

Development

### Build info

```json
{
    "built": "2023-08-06T13:10:46+00:00",
    "ref": "refs/tags/v0.5-alpha.8",
    "sha": "aa2922362e44ff498a4dd4b817f75e250f191726",
    "actor": "Revyn112",
    "event_name": "manual",
    "pretty_release_name": "stable/v0.5-alpha.8",
    "version": "v0.5.0-HEAD.aa29223"
}
```

### Describe the bug

Hello,

in my flight i decided to climb to FL400. The plane let me maximal select FL391. The max Altitude is in my opinion 41450ft.

Greetings,
Sascha.

### Expected behavior

It should be able to climb to 41450ft.

### Steps to reproduce

Try to climb to FL400 or above.

**Comment by st3ph29** [comment]
Max level available  or optimal level is not a matter of opinion. FL is  trigered by your actual weight, but as you're the pilot in command feels free to go over the limit.

**Comment by SandaleAir** [comment]
Hello,

i found it. I used the Variables FBWA320N-FCU ALT dec and FBWA320N-FCU ALT inc for set the Altitude in the FCU. I this case you can't set it above 39100 feet.

Greetings,
Sascha Schuh.
